---
title: "cielo2_descriptives"
author: "Ashley"
date: '2022-11-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(reshape2)
library(dplyr)
library(ggplot2)
```

## Cielo 2 Descriptives

This Markdown doc includes Cielo 2 descriptive data. 

Ashley- think about what other things you'd like to visualize descriptively with the data that we have. What would be useful for us/the reader to see? What info do you need for the manuscript? 

```{r reading in data}
d_all <- read_csv("\\cielo2_cleaneddata_real.csv")

```

```{r god certainty plot}
godcertainty_plot <- ggplot(d_all, aes(sort_god_sure)) +
  geom_bar(fill='pink') +
  labs(x='Degrees of Certainty', y="Number of Participants", title ="Certainty of God's Realness") +
  theme_minimal()
godcertainty_plot
```




```{r sort data vis}
########################################################################################
# ASHLEY START HERE AND LET HL KNOW WHEN YOU'VE GOT IT (OR IF YOU NEED HELP)
########################################################################################

# here, we're creating a new dataframe for a subset of our data that we want to look at (the sort questions). when we create a new dataframe, we want to use the select function in the dplyr package loaded in our setupchunk. which columns do we want to select to include in this subset? probably all of the sort_ columns and pid, and gender? maybe age too. start there.
d_sort <- dplyr::select(d_all, gender, sort_germ, sort_tooth, sort_vitamin, sort_mermaid, sort_elf, sort_fairy,
                         sort_soul, sort_god, sort_santa, sort_elf, contains("pid"))

#i'm subsetting out the other gender because they are only one participant in cielo1
d_sort<-subset(d_sort, gender!="3")

# let's reshape our data to tall format so we can include all of the same plots on the same figure watch this youtube video for what it means to reshape our data: https://www.youtube.com/watch?v=eLCKL7BNIAk&ab_channel=StatisticsGlobe

# hl added the reshape2 library to our setup chunk. this is the library that the melt function is in (just fyi)
d_sort <- melt(d_sort, id.vars= c("pid", "gender"))

#let's view our tall data now. did we do it right?

# here, i'm making a dataframe with frequency counts added in (just to see what kind of figure i should end up with)
#only do this with a subset of your data, including the "sort" variables or "sort_sure", for example. my sort data was called exist in my code, so that's why you see d_exist here
d_sort_counts <- table(d_sort$value, d_sort$variable, d_sort$gender)
addmargins(d_sort_counts)
round(prop.table(d_sort_counts,2)*100,digits=0)
sort_count <- as.data.frame(d_sort_counts) 
sort_count

# creating our ggplot for all exist questions including both genders together. i'm labeling it p_exist because we're making a plot for the exist questions
p_sort <- ggplot(data = sort_count, aes(x = Var2, y = Freq, fill = Var1)) +
       geom_bar(stat = "identity", width = .5) +
      geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), color="black", size=3) +
      theme_classic() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Response") +
      theme(axis.text.x = element_text(angle=20))
p_sort
# fixing the x axis labels
p_sort <- p_sort + scale_x_discrete(labels=c("sort_germ" = "Germs", "sort_tooth" = "Tooth Fairy", "sort_vitamin" = "Vitamins", "sort_mermaid" = "Mermaids", "sort_elf" = "Elves", "sort_fairy" = "Fairies", "sort_soul" = "Souls", "sort_god" = "God", "sort_santa" = "Santa"))

# faceting by gender
#facet wrap means "group by"
p_sort <- p_sort + facet_wrap(~Var3, ncol = 2) +
    theme(panel.spacing = unit(1, "lines"))
p_sort
#coord_flip switches x and y axes visually
#p_sort + coord_flip()
#at this point, we need to check to see what the 1 and 2 values are (gender options or sureness options)
# i can do this by tallying the number of genders and seeing if they sum to the total count of that variable
# could also not facet by gender
```


```{r clustered bar chart for real/pretend questions}

#remember, if we use ggplot and do not name it anything (p_exist <- ggplot) then the figure will automatically pop up outside of our chunk without having to call anything
ggplot(data = df_ec2, aes(Var2, Freq)) + 
  geom_bar(aes(fill = Var3), stat = "identity", position = "dodge") +
      theme_minimal() +
      labs(title="Children's responses to real or pretend questions", x ="Item", y = "Counts", fill = "Age") +
      scale_x_discrete(labels=c("exist_germs" = "Germs", "exist_tooth" = "Tooth Fairy", "exist_vitamins" = "Vitamins", "exist_merm" = "Mermaids", "exist_elf" = "Elves", "exist_fairy" = "Fairies", "exist_soul" = "Souls", "exist_god" = "God", "exist_santa" = "Santa")) +
    scale_fill_brewer(palette = "Paired") +
  facet_wrap(~Var1, ncol = 1)

```
##

